// Static eval multipliers
#define MINIMAX_TOTAL_SCORE_MUL 25
#define MINIMAX_TOTAL_CHIPS_MUL 1
#define MINIMAX_TOTAL_GOLD_MUL 1
#define MINIMAX_RES_CNT_MUL -8
#define MINIMAX_NUM_CARDS_MUL 15

#define MINIMAX_CLOSE_TO_NOBLE_MUL 10
#define MINIMAX_CLOSE_TO_NOBLE_MARGIN 1
